# Generated by Django 6.0.7 on 2026-07-26 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_backfill_statement_file_hash'),
        ('tracker', '0004_seed_default_categories'),
    ]

    operations = [
    ]
