import {
  Brain,
  TrendingUp,
  Wallet,
  TriangleAlert,
  Sparkles,
} from "lucide-react";

function truncate(value, length = 90) {
  if (!value) return "";
  if (value.length <= length) return value;
  const trimmed = value.slice(0, length);
  const lastSpace = trimmed.lastIndexOf(" ");
  return `${(lastSpace > 0 ? trimmed.slice(0, lastSpace) : trimmed).trim()}…`;
}

export default function AIInsightCard({ data }) {
  const recommendations = data?.ai_recommendations ?? [];
  const highestCategory = data?.highest_expense_category ?? "your top category";
  const highestCategoryAmount = data?.spending_per_category?.[0]?.amount;
  const formattedHighestCategoryAmount = highestCategoryAmount != null
    ? `₹${Number(highestCategoryAmount).toLocaleString("en-IN")}`
    : "—";
  const savingsHint = data?.ai_budget_advice
    ? truncate(data.ai_budget_advice, 140)
    : `Reduce ${highestCategory.toLowerCase()} expenses.`;
  const topRecommendation = truncate(recommendations[0], 140) || "Review your largest expense categories.";
  const prediction = data?.predicted_next_month_spend
    ? `Estimated spend: ₹${Number(data.predicted_next_month_spend).toLocaleString("en-IN")}`
    : truncate(recommendations[1], 70) || "Keep discretionary spend under control.";
  const detailSummary = truncate(data?.ai_spending_summary, 120) || "Get a concise AI recommendation once your statement is processed.";

  return (
    <div className="bg-gradient-to-r from-blue-600 via-indigo-600 to-violet-700 rounded-3xl shadow-lg p-8 text-white">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-12 h-12 rounded-2xl bg-white/20 flex items-center justify-center">
            <Brain size={26} />
          </div>

          <div>
            <h2 className="text-2xl font-bold">
              AI Financial Insight
            </h2>

            <p className="text-blue-100 text-sm mt-1">
              Personalized recommendations generated by AI
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2 rounded-full bg-white/20 px-4 py-2 text-sm">
          <Sparkles size={16} />
          AI Generated
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-5 mt-8">
        <div className="rounded-2xl bg-white/10 backdrop-blur-md p-5">
          <TrendingUp className="mb-4" />

          <p className="text-sm text-blue-100">
            Highest Spending
          </p>

          <h3 className="text-2xl font-bold mt-2">
            {highestCategory}
          </h3>

          <p className="mt-2 text-sm text-blue-100">
            {formattedHighestCategoryAmount}
          </p>
        </div>

        <div className="rounded-2xl bg-white/10 backdrop-blur-md p-5">
          <Wallet className="mb-4" />

          <p className="text-sm text-blue-100">
            Savings Opportunity
          </p>

          <h3 className="text-2xl font-bold mt-2">
            {savingsHint}
          </h3>

          <p className="mt-2 text-sm text-blue-100">
            {topRecommendation}
          </p>
        </div>

        <div className="rounded-2xl bg-white/10 backdrop-blur-md p-5">
          <TriangleAlert className="mb-4" />

          <p className="text-sm text-blue-100">
            Next Month Prediction
          </p>

          <h3 className="text-2xl font-bold mt-2">
            {prediction}
          </h3>

          <p className="mt-2 text-sm text-blue-100">
            {truncate(recommendations[2], 70) || "Monitor your budget weekly for better control."}
          </p>
        </div>
      </div>

      <div className="mt-8 rounded-2xl bg-white/10 backdrop-blur-md p-6">
        <h3 className="font-semibold text-lg">
          AI Recommendation
        </h3>

        <p className="mt-3 text-blue-100 leading-7">
          {detailSummary}
        </p>

        <button className="mt-5 inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-5 py-3 text-sm font-semibold text-white transition hover:bg-white/20">
          View Details →
        </button>
      </div>
    </div>
  );
}
