import {
  Brain,
  TrendingUp,
  Wallet,
  TriangleAlert,
  Sparkles,
} from "lucide-react";

export default function AIInsightCard({ data }) {
  const recommendations = data?.ai_recommendations ?? [];

  return (
    <div className="bg-gradient-to-r from-blue-600 via-indigo-600 to-violet-700 rounded-3xl shadow-lg p-8 text-white">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-12 h-12 rounded-2xl bg-white/20 flex items-center justify-center">
            <Brain size={26} />
          </div>

          <div>
            <h2 className="text-2xl font-bold">
              AI Financial Insight
            </h2>

            <p className="text-blue-100 text-sm mt-1">
              Personalized recommendations generated by AI
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2 rounded-full bg-white/20 px-4 py-2 text-sm">
          <Sparkles size={16} />
          AI Generated
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-5 mt-8">
        <div className="rounded-2xl bg-white/10 backdrop-blur-md p-5">
          <TrendingUp className="mb-4" />

          <p className="text-sm text-blue-100">
            Highest Spending
          </p>

          <h3 className="text-2xl font-bold mt-2">
            {data?.highest_expense_category}
          </h3>

          <p className="mt-2 text-sm text-blue-100">
            {data?.ai_spending_summary}
          </p>
        </div>

        <div className="rounded-2xl bg-white/10 backdrop-blur-md p-5">
          <Wallet className="mb-4" />

          <p className="text-sm text-blue-100">
            Savings Opportunity
          </p>

          <h3 className="text-2xl font-bold mt-2">
            {data?.ai_budget_advice}
          </h3>

          <p className="mt-2 text-sm text-blue-100">
            {recommendations[0]}
          </p>
        </div>

        <div className="rounded-2xl bg-white/10 backdrop-blur-md p-5">
          <TriangleAlert className="mb-4" />

          <p className="text-sm text-blue-100">
            Next Month Prediction
          </p>

          <h3 className="text-2xl font-bold mt-2">
            {recommendations[1]}
          </h3>

          <p className="mt-2 text-sm text-blue-100">
            {recommendations[2]}
          </p>
        </div>
      </div>

      <div className="mt-8 rounded-2xl bg-white/10 backdrop-blur-md p-6">
        <h3 className="font-semibold text-lg">
          AI Recommendation
        </h3>

        <p className="mt-3 text-blue-100 leading-7">
          {data?.ai_spending_summary}
        </p>
      </div>
    </div>
  );
}
